# Generated by Django 5.1.4 on 2025-11-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('todo_type', models.CharField(choices=[('pr', 'Prayer'), ('st', 'Study'), ('wo', 'Work'), ('ho', 'Home'), ('pu', 'People'), ('pl', 'Play')], default='st', max_length=2)),
                ('status', models.CharField(choices=[('to', 'Todo'), ('pr', 'Progress'), ('co', 'Complete'), ('ar', 'Archived')], default='to', max_length=2)),
                ('created_on', models.DateField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
