version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend/karma:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./frontend/karma:/app
    working_dir: /app
    ports:
      - "8080:8080"
