# Generated by Django 5.1.4 on 2024-12-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=32)),
                ('date', models.DateField(auto_now_add=True)),
                ('review', models.CharField(choices=[('pe', 'Pending'), ('sa', 'Satisfied'), ('us', 'Unsatisfied')], default='pe', max_length=2)),
            ],
        ),
    ]
