# Generated by Django 5.1.4 on 2024-12-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karma',
            old_name='task',
            new_name='Karma',
        ),
    ]
