# Generated by Django 5.1.4 on 2024-12-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_task_karma_karma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pe', 'Pending'), ('co', 'Complete')], default='pe', max_length=2)),
                ('due_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
