# Generated by Django 5.1.4 on 2024-12-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
