# Generated by Django 5.1.4 on 2024-12-18 06:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='karma',
            name='due_date',
            field=models.DateField(default=app.models.next_day_date),
        ),
        migrations.AddField(
            model_name='karma',
            name='type',
            field=models.CharField(choices=[('da', 'Daily'), ('re', 'Regular')], default='re', max_length=2),
        ),
    ]
