# Generated by Django 5.1.4 on 2024-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_karma_due_date_karma_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
