# Generated by Django 5.1.4 on 2024-12-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dayreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karma',
            old_name='Karma',
            new_name='karma',
        ),
    ]
