# Generated by Django 5.1.4 on 2024-12-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_karma_karma_karma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karma',
        ),
    ]
