# Generated by Django 5.1.4 on 2024-12-22 07:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_karma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('karma', models.CharField(max_length=32)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=app.models.next_day_date)),
                ('daily', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('pr', 'Prayer'), ('st', 'Study'), ('wo', 'Work'), ('ho', 'Home'), ('pu', 'People')], default='st', max_length=2)),
                ('review', models.CharField(choices=[('pe', 'Pending'), ('sa', 'Satisfied'), ('us', 'Unsatisfied')], default='pe', max_length=2)),
            ],
        ),
    ]
