# Generated by Django 5.1.4 on 2024-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karma',
            name='karma',
            field=models.CharField(max_length=128),
        ),
    ]
