# Generated by Django 5.1.4 on 2025-01-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_karma_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karma',
            name='type',
            field=models.CharField(choices=[('pr', 'Prayer'), ('st', 'Study'), ('wo', 'Work'), ('ho', 'Home'), ('pu', 'People'), ('pl', 'Play')], default='st', max_length=2),
        ),
    ]
