# Generated by Django 5.1.4 on 2025-01-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_karma_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karma',
            name='date',
            field=models.DateField(),
        ),
    ]
