# Generated by Django 5.1.4 on 2025-01-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_karma_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karma',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='karma',
            name='due_date',
        ),
    ]
