# Generated by Django 5.1.4 on 2025-01-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_karma_daily_remove_karma_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('todo_type', models.CharField(choices=[('pr', 'Prayer'), ('st', 'Study'), ('wo', 'Work'), ('ho', 'Home'), ('pu', 'People'), ('pl', 'Play')], default='st', max_length=2)),
                ('status', models.CharField(choices=[('to', 'Todo'), ('pr', 'Progress'), ('co', 'Complete')], default='to', max_length=2)),
                ('created_on', models.DateField(auto_now=True)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
