# Generated by Django 5.1.4 on 2025-03-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Karma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("karma", models.CharField(max_length=128)),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pr", "Prayer"),
                            ("st", "Study"),
                            ("wo", "Work"),
                            ("ho", "Home"),
                            ("pu", "People"),
                            ("pl", "Play"),
                        ],
                        default="st",
                        max_length=2,
                    ),
                ),
                (
                    "review",
                    models.CharField(
                        choices=[
                            ("pe", "Pending"),
                            ("sa", "Satisfied"),
                            ("us", "Unsatisfied"),
                        ],
                        default="pe",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reflection", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo", models.CharField(max_length=100)),
                (
                    "todo_type",
                    models.CharField(
                        choices=[
                            ("pr", "Prayer"),
                            ("st", "Study"),
                            ("wo", "Work"),
                            ("ho", "Home"),
                            ("pu", "People"),
                            ("pl", "Play"),
                        ],
                        default="st",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to", "Todo"),
                            ("pr", "Progress"),
                            ("co", "Complete"),
                        ],
                        default="to",
                        max_length=2,
                    ),
                ),
                ("created_on", models.DateField(auto_now=True)),
                ("deadline", models.DateField()),
            ],
        ),
    ]
