# Generated by Django 5.1.4 on 2025-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="completed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
