# Generated by Django 5.1.4 on 2025-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_todo_archived_todo_completed_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="archived",
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("to", "Todo"),
                    ("pr", "Progress"),
                    ("co", "Complete"),
                    ("ar", "Archived"),
                ],
                default="to",
                max_length=2,
            ),
        ),
    ]
