# Generated by Django 5.1.4 on 2025-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
